apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup

spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from $(workspaces.source.path) ..."
    
        if [ -d "$(workspaces.source.path)" ] ; then
            rm -rf "$(workspaces.source.path:?)"/*
            rm -rf "$(workspaces.source.path)"/.[!.]*
            rm -rf "$(workspaces.source.path)"/..?*
        fi 

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose

spec: 
  workspaces:
    - name: source
  params:
    - name: args
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)
